function output = importfileGPS(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

    %  Auto-generated by MATLAB on 12-Jun-2013 15:13:46

    DELIMITER = '\t';
    HEADERLINES = 0;

    % Import the file
    newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

    % import time
    formatIn = 'HH:MM:SS';
    for i=1:length(newData1.textdata)
        DateString = newData1.textdata{i};
        temp = datevec(DateString,formatIn);
        output(i,1) = temp(4)*3600 + temp(5)*60 + temp(6);
    end
    output=output-output(1,1);
    output(:,2:4) = newData1.data;

end


